import axios from 'axios';
import {
  AlertCircle as AlertIcon,
  Bot,
  CheckCircle as CheckIcon,
  X as CloseIcon,
  PlusCircle as PlusIcon,
  Upload as UploadIcon,
} from 'lucide-react';
import { useEffect, useState } from 'react';
import { useLocation, useNavigate } from 'react-router-dom';
import Loader from '../../components/Loader';

const AddQuestion = () => {
  const [fileName, setFileName] = useState('');
  const [teacherName, setTeacherName] = useState('');
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState(null);
  const [showDeptSuggestions, setShowDeptSuggestions] = useState(false);
  const [showSubjSuggestions, setShowSubjSuggestions] = useState(false);
  const [userDetails, setUserDetails] = useState(null);
  const [teacherId, setTeacherId] = useState('');
  const [showModal, setShowModal] = useState(false);
  const [modalType, setModalType] = useState(''); // "success" | "error"
  const [modalMessage, setModalMessage] = useState('');

  const [tags, setTags] = useState([{ tag: '', weightage: '' }]);
  const [totalWeightage, setTotalWeightage] = useState(0);
  const [formInput, setFormInput] = useState({
    name: '',
    department: '',
    subjectName: '',
    year: '',
    openDate: '',
    closeDate: '',
    openTime: '',
    closeTime: '',
    questionperstudent: '',
    examDurationMinutes: '60',
    allowFlexibleTiming: false,
  });
  
  // State to hold the file generated by the AI Factory
  const [fileToSubmit, setFileToSubmit] = useState(null);

  const navigate = useNavigate();
  const location = useLocation();

  // Mock data (Unchanged)
  const departments = ['Assessment'];
  const subjects = {
    Assessment: {
      1: ['CMA US Scholarship'],
      2: ['Data Structures', 'Algorithms', 'Operating Systems', 'Database Systems', 'Computer Architecture'],
      3: ['Artificial Intelligence', 'Machine Learning', 'Cloud Computing', 'Cyber Security', 'Big Data Analytics'],
    },
  };
  const [filteredDepts, setFilteredDepts] = useState([]);
  const [filteredSubjects, setFilteredSubjects] = useState([]);


  // --- Lifecycle and State Effects ---
  useEffect(() => {
    // This effect handles the data passed from AIQuizFactory
    if (location.state?.aiQuizData) {
      const { tags, fileName, csvContent } = location.state.aiQuizData;
      if (tags?.length > 0) setTags(tags);
      setFileName(fileName);
      // Create a File object from the CSV content and store it in state
      setFileToSubmit(new File([csvContent], fileName, { type: 'text/csv' }));
      // Clear the location state to prevent re-triggering on refresh
      window.history.replaceState({}, document.title);
    }
  }, [location.state]);

  useEffect(() => {
    const total = tags.reduce((sum, tag) => sum + parseFloat(tag.weightage || 0), 0);
    setTotalWeightage(total);
  }, [tags]);

  useEffect(() => {
    try {
      const token = sessionStorage.getItem('token');
      if (!token) throw new Error('Session expired');
      const payloadBase64 = token.split('.')[1];
      const decodedPayload = JSON.parse(
        window.atob(payloadBase64.replace(/-/g, '+').replace(/_/g, '/')),
      );
      setTeacherName(decodedPayload.userDetails.name);
      setUserDetails(decodedPayload.userDetails);
      setTeacherId(decodedPayload.userDetails.teacher_id);
    } catch (err) {
      setError('Invalid or expired session. Please log in again.');
    } finally {
      setIsLoading(false);
    }
  }, [navigate]);

  // --- UI Helpers (Unchanged) ---
  const closeModal = () => setShowModal(false);
  const showSuccess = (msg) => { setModalType('success'); setModalMessage(msg); setShowModal(true); };
  const showError = (msg) => { setModalType('error'); setModalMessage(msg); setShowModal(true); };
  const handleInputChange = (e, field) => {
    const value = e.target.type === 'checkbox' ? e.target.checked : e.target.value;
    setFormInput((prev) => ({ ...prev, [field]: value }));
    if (field === 'department') {
      const filtered = departments.filter((d) => d.toLowerCase().includes(value.toLowerCase()));
      setFilteredDepts(filtered); setShowDeptSuggestions(true); setFormInput((prev) => ({ ...prev, subjectName: '' }));
    }
    if (field === 'subjectName') {
      const list = subjects[formInput.department]?.[formInput.year] || [];
      const filtered = list.filter((s) => s.toLowerCase().includes(value.toLowerCase()));
      setFilteredSubjects(filtered); setShowSubjSuggestions(true);
    }
    if (field === 'year') { setFormInput((prev) => ({ ...prev, subjectName: '', year: value })); }
  };
  const handleSuggestionClick = (value, field) => {
    setFormInput((prev) => ({ ...prev, [field]: value }));
    if (field === 'department') { setShowDeptSuggestions(false); } else { setShowSubjSuggestions(false); }
  };
  const handleTagChange = (index, field, value) => {
    const next = [...tags];
    next[index][field] = value;
    setTags(next);
  };
  const addTag = () => setTags([...tags, { tag: '', weightage: '' }]);
  const removeTag = (i) => { setTags(tags.filter((_, idx) => idx !== i)); };
  
  const handleGoToAiFactory = () => navigate('/teacher/ai-quiz-factory');
  
  // --- Submission Logic ---
  const handleSubmit = async (e) => {
    e.preventDefault();
    // Basic validation
    if (Math.abs(totalWeightage - 100) > 0.1) {
        showError("Total tag weightage must be exactly 100%.");
        return;
    }

    try {
      setIsLoading(true);
      const token = sessionStorage.getItem('token');
      if (!token) throw new Error('Session expired');

      const formData = new FormData();

      // Append all form fields from state
      for (const key in formInput) {
        formData.append(key, formInput[key]);
      }
      formData.append('teacher_id', teacherId);
      formData.append('tags', JSON.stringify(tags));

      // --- FIX: Logic to handle both AI-generated and manually uploaded files ---
      // 1. Prioritize the file from the AI Factory (stored in state)
      if (fileToSubmit) {
        formData.append('file', fileToSubmit);
      } 
      // 2. Fallback to the manual file input if no AI file exists
      else {
        const fileInput = e.target.elements.file;
        if (fileInput && fileInput.files[0]) {
          formData.append('file', fileInput.files[0]);
        } else {
          // Optional: You could throw an error if no file is provided at all
          // showError("Please upload a CSV file.");
          // setIsLoading(false);
          // return;
        }
      }
      // --- END FIX ---

      await axios.post('http://localhost:5000/api/v1/assessments', formData, {
        headers: {
          Authorization: `Bearer ${token}`,
          // 'Content-Type': 'multipart/form-data' is set automatically by browsers for FormData
        },
      });
      showSuccess('Assessment created successfully!');
    } catch (err) {
      console.error(err);
      const errorMessage = err.response?.data?.message || 'Submission failed. Please check your network connection and try again.';
      showError(errorMessage);
    } finally {
      setIsLoading(false);
    }
  };


  if (isLoading) return <Loader/>;
  if (error) return <p className="p-6 text-center text-red-600">{error}</p>;

  // --- Render (Unchanged) ---
  return (
    <div className="p-6 max-w-4xl mx-auto grid gap-6">
      {/* Card wrapper – mirrors dashboard style */}
      <div className="bg-white rounded-lg border border-slate-200 shadow-sm p-6 flex flex-col gap-6">
        <header className="flex items-center justify-between pb-4 border-b border-slate-200">
          <h1 className="text-md text-slate-600">You are creating assessment as <span className='font-medium'>{teacherName}</span></h1>
        </header>

        <form onSubmit={handleSubmit} className="space-y-6">
          {/* Grid – two columns on md+ */}
          <div className="grid gap-4 md:grid-cols-2">
            {/* Teacher ID (readonly) */}
            <div className="flex flex-col gap-1">
              <label className="text-sm font-medium text-slate-600">Teacher ID</label>
              <input
                type="text"
                readOnly
                value={teacherId}
                className="w-full bg-slate-100 border border-slate-200 rounded-md px-3 py-2 text-sm text-slate-500"
              />
            </div>

            {/* Assessment Name */}
            <div className="flex flex-col gap-1">
              <label className="text-sm font-medium text-slate-600">Assessment Name</label>
              <input
                type="text"
                name="name"
                placeholder="Assessment Name"
                className="w-full border border-slate-300 rounded-md px-3 py-2 text-sm focus:outline-none focus:ring-blue-500 focus:border-blue-500"
                value={formInput.name}
                onChange={(e) => handleInputChange(e, 'name')}
                required
              />
            </div>

            {/* Department with suggestions */}
            <div className="relative flex flex-col gap-1 md:col-span-1">
              <label className="text-sm font-medium text-slate-600">Department</label>
              <input
                type="text"
                name="department"
                placeholder="Department"
                value={formInput.department}
                onChange={(e) => handleInputChange(e, 'department')}
                className="w-full border border-slate-300 rounded-md px-3 py-2 text-sm focus:outline-none focus:ring-blue-500 focus:border-blue-500"
                required
              />
              {showDeptSuggestions && filteredDepts.length > 0 && (
                <div className="absolute z-10 mt-1 w-full bg-white border border-slate-200 rounded-md shadow-lg max-h-48 overflow-auto top-full">
                  {filteredDepts.map((d) => (
                    <button
                      type="button"
                      key={d}
                      className="block w-full text-left px-3 py-2 text-sm hover:bg-slate-100"
                      onClick={() => handleSuggestionClick(d, 'department')}
                    >
                      {d}
                    </button>
                  ))}
                </div>
              )}
            </div>

            {/* Year select */}
            <div className="flex flex-col gap-1">
              <label className="text-sm font-medium text-slate-600">Year</label>
              <select
                name="year"
                value={formInput.year}
                onChange={(e) => handleInputChange(e, 'year')}
                className="w-full border border-slate-300 rounded-md px-3 py-2 text-sm focus:outline-none focus:ring-blue-500 focus:border-blue-500"
                required
              >
                <option value="">Select Year</option>
                <option value="1">1st Year</option>
                <option value="2">2nd Year</option>
                <option value="3">3rd Year</option>
              </select>
            </div>

            {/* Subject name with suggestions */}
            <div className="relative flex flex-col gap-1 md:col-span-2">
              <label className="text-sm font-medium text-slate-600">Subject Name</label>
              <input
                type="text"
                name="subjectName"
                placeholder="Subject Name"
                value={formInput.subjectName}
                disabled={!formInput.department || !formInput.year}
                onChange={(e) => handleInputChange(e, 'subjectName')}
                className="w-full border border-slate-300 rounded-md px-3 py-2 text-sm focus:outline-none focus:ring-blue-500 focus:border-blue-500 disabled:bg-slate-100"
                required
              />
              {showSubjSuggestions && filteredSubjects.length > 0 && (
                <div className="absolute z-10 mt-1 w-full bg-white border border-slate-200 rounded-md shadow-lg max-h-48 overflow-auto top-full">
                  {filteredSubjects.map((s) => (
                    <button
                      type="button"
                      key={s}
                      className="block w-full text-left px-3 py-2 text-sm hover:bg-slate-100"
                      onClick={() => handleSuggestionClick(s, 'subjectName')}
                    >
                      {s}
                    </button>
                  ))}
                </div>
              )}
            </div>

            {/* Dates & times */}
            {[
              { field: 'openDate', label: 'Open Date', type: 'date' },
              { field: 'openTime', label: 'Start Time', type: 'time' },
              { field: 'closeDate', label: 'Close Date', type: 'date' },
              { field: 'closeTime', label: 'End Time', type: 'time' },
            ].map(({ field, label, type }) => (
              <div key={field} className="flex flex-col gap-1">
                <label className="text-sm font-medium text-slate-600">{label}</label>
                <input
                  type={type}
                  name={field}
                  value={formInput[field]}
                  onChange={(e) => handleInputChange(e, field)}
                  className="w-full border border-slate-300 rounded-md px-3 py-2 text-sm focus:outline-none focus:ring-blue-500 focus:border-blue-500"
                  required
                />
              </div>
            ))}

            {/* Questions per student */}
            <div className="flex flex-col gap-1">
              <label className="text-sm font-medium text-slate-600">Questions per Student</label>
              <input
                type="number"
                name="questionperstudent"
                placeholder="e.g. 10"
                min="1"
                value={formInput.questionperstudent}
                onChange={(e) => handleInputChange(e, 'questionperstudent')}
                className="w-full border border-slate-300 rounded-md px-3 py-2 text-sm focus:outline-none focus:ring-blue-500 focus:border-blue-500"
                required
              />
            </div>

            {/* Exam duration */}
            <div className="flex flex-col gap-1">
              <label className="text-sm font-medium text-slate-600">Exam Duration (minutes)</label>
              <input
                type="number"
                name="examDurationMinutes"
                min="1"
                value={formInput.examDurationMinutes}
                onChange={(e) => handleInputChange(e, 'examDurationMinutes')}
                className="w-full border border-slate-300 rounded-md px-3 py-2 text-sm focus:outline-none focus:ring-blue-500 focus:border-blue-500"
                required
              />
            </div>
          </div>

          {/* Tags section */}
          <div className="flex flex-col gap-4">
            <h2 className="text-sm font-medium text-slate-600">Question Tags & Weightage</h2>
            <div className="space-y-3">
              {tags.map((t, idx) => (
                <div key={idx} className="grid gap-2 md:grid-cols-[1fr_120px_auto] items-center">
                  <input
                    type="text"
                    placeholder="Tag (e.g. CS)"
                    value={t.tag}
                    onChange={(e) => handleTagChange(idx, 'tag', e.target.value)}
                    className="border border-slate-300 rounded-md px-3 py-2 text-sm focus:outline-none focus:ring-blue-500 focus:border-blue-500"
                    required
                  />
                  <input
                    type="number"
                    placeholder="Weightage %"
                    min="0"
                    max="100"
                    step="0.1"
                    value={t.weightage}
                    onChange={(e) => handleTagChange(idx, 'weightage', e.target.value)}
                    className="border border-slate-300 rounded-md px-3 py-2 text-sm focus:outline-none focus:ring-blue-500 focus:border-blue-500"
                    required
                  />
                  {tags.length > 1 && (
                    <button
                      type="button"
                      onClick={() => removeTag(idx)}
                      className="p-2 rounded-md hover:bg-slate-100 transition"
                    >
                      <CloseIcon className="w-4 h-4 text-slate-500" />
                    </button>
                  )}
                </div>
              ))}
            </div>
            <div className="flex items-center justify-between text-sm">
              <button
                type="button"
                onClick={addTag}
                className="flex items-center gap-2 font-medium text-blue-600 hover:underline"
              >
                <PlusIcon className="w-4 h-4" /> Add Tag
              </button>
              <span
                className={`font-medium ${Math.abs(totalWeightage - 100) > 0.1 ? 'text-red-600' : 'text-slate-600'}`}
              >
                Total: {totalWeightage}%
              </span>
            </div>
          </div>

          {/* File upload */}
          <div className="flex flex-col gap-1">
            <label className="text-sm font-medium text-slate-600">Upload CSV</label>
            <div className="relative flex items-center gap-3 border border-slate-300 rounded-md px-3 py-2 text-sm">
              <UploadIcon className="w-4 h-4 text-slate-500" />
              <input
                type="file"
                id="file-upload"
                name="file"
                accept=".csv"
                onChange={(e) => {
                    setFileName(e.target.files?.[0]?.name || '');
                    // Clear the AI file if a manual one is chosen
                    if(e.target.files?.[0]) setFileToSubmit(null);
                }}
                className="absolute inset-0 opacity-0 cursor-pointer"
              />
              <span className="truncate select-none">{fileName || 'Choose CSV file'}</span>
            </div>
          </div>

          {/* AI Factory Section */}
          <div className="md:col-span-2 p-4 bg-blue-50/50 border-2 border-dashed border-blue-200 rounded-lg space-y-4">
            <div className="flex items-center gap-2">
              <Bot className="w-5 h-5 text-blue-600" />
              <h4 className="font-semibold text-slate-800">Generate Questions with AI</h4>
            </div>
            <p className="text-sm text-slate-600">Alternatively, use our AI to generate a question CSV for you based on a PDF document.</p>
            <div className="text-left">
              <button type="button" onClick={handleGoToAiFactory} className="inline-flex items-center gap-2 px-4 py-2 text-sm font-semibold bg-blue-600 text-white rounded-lg hover:bg-blue-700">Go to AI Quiz Factory</button>
            </div>
          </div>

          {/* Submit button */}
          <div className="flex justify-end">
            <button
              type="submit"
              disabled={isLoading}
              className="bg-blue-600 text-white px-6 py-2 rounded-md font-semibold hover:bg-blue-700 transition disabled:opacity-60"
            >
              {isLoading ? 'Uploading…' : 'Upload Questions'}
            </button>
          </div>
        </form>
      </div>

      {/* Modal */}
      {showModal && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-900/50 p-4">
          <div className="bg-white rounded-lg shadow-lg max-w-sm w-full p-6 space-y-4">
            <div className="flex items-center gap-2">
              {modalType === 'success' ? <CheckIcon className="w-5 h-5 text-green-600" /> : <AlertIcon className="w-5 h-5 text-red-600" />}
              <h3 className="text-base font-semibold text-slate-800">{modalType === 'success' ? 'Success' : 'Error'}</h3>
            </div>
            <p className="text-sm text-slate-600">{modalMessage}</p>
            <div className="flex justify-end gap-2">
              <button
                onClick={closeModal}
                className="bg-slate-100 text-slate-700 px-4 py-1.5 rounded-md text-sm font-medium hover:bg-slate-200 transition"
              >
                Close
              </button>
              {modalType === 'success' && (
                <button
                  onClick={() => { closeModal(); navigate('/teacher-dashboard'); }}
                  className="bg-blue-600 text-white px-4 py-1.5 rounded-md text-sm font-medium hover:bg-blue-700 transition"
                >
                  Go to Dashboard
                </button>
              )}
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default AddQuestion;

