import axios from 'axios';
import {
  AlertCircle as AlertIcon,
  Bot,
  CheckCircle as CheckIcon,
  X as CloseIcon,
  PlusCircle as PlusIcon,
  Upload as UploadIcon,
} from 'lucide-react';
import { useEffect, useState } from 'react';
import { useLocation, useNavigate } from 'react-router-dom';
import Loader from '../../components/Loader'; // Global loading spinner
import { API_BASE_URL } from '../../config/constants'; // Import the common API base URL

/**
 * AddQuestion component allows teachers to create new assessments by providing details
 * and uploading a CSV file containing questions. It also integrates with an AI Quiz Factory
 * to generate question CSVs.
 *
 * @returns {JSX.Element} The assessment creation form.
 */
const AddQuestion = () => {
  // State to display the name of the selected file.
  const [fileName, setFileName] = useState('');
  // State to store the teacher's name (for display).
  const [teacherName, setTeacherName] = useState('');
  // State to manage overall loading status.
  const [isLoading, setIsLoading] = useState(true);
  // State to store any error messages during initial data load or form submission.
  const [error, setError] = useState(null);
  // States for department and subject suggestion dropdowns.
  const [showDeptSuggestions, setShowDeptSuggestions] = useState(false);
  const [showSubjSuggestions, setShowSubjSuggestions] = useState(false);
  // Authenticated user details.
  const [userDetails, setUserDetails] = useState(null);
  // Teacher's unique ID.
  const [teacherId, setTeacherId] = useState('');
  // States for modal visibility and content (success/error messages).
  const [showModal, setShowModal] = useState(false);
  const [modalType, setModalType] = useState(''); // "success" | "error"
  const [modalMessage, setModalMessage] = useState('');

  // States for question tags and their weightages.
  const [tags, setTags] = useState([{ tag: '', weightage: '' }]);
  const [totalWeightage, setTotalWeightage] = useState(0);

  // Form input fields for assessment details.
  const [formInput, setFormInput] = useState({
    name: '',
    department: '',
    subjectName: '',
    year: '',
    openDate: '',
    closeDate: '',
    openTime: '',
    closeTime: '',
    questionperstudent: '',
    examDurationMinutes: '60',
    allowFlexibleTiming: false,
  });

  // State to hold the file generated by the AI Factory (a File object).
  const [fileToSubmit, setFileToSubmit] = useState(null);

  const navigate = useNavigate(); // Hook for programmatic navigation.
  const location = useLocation(); // Hook to access location state (for AI-generated data).

  // --- Mock Data for Departments and Subjects ---
  // In a real application, these would typically be fetched from an API.
  const departments = ['Computer Science', 'Cyber Security', 'AIML', 'AIDS', 'IT', 'CA'];
  const subjects = {
      'Computer Science': {
          '1': ['Programming Basics', 'Discrete Mathematics', 'Introduction to Computer Systems', 'Fundamentals of Data Communication','Software Engineering Principles'],
          '2': ['Data Structures', 'Algorithms', 'Operating Systems', 'Database Systems','Computer Architecture'],
          '3': ['Artificial Intelligence', 'Machine Learning', 'Cloud Computing', 'Cyber Security','Big Data Analytics']
      },
      'IT': {
          '1': ['IT Fundamentals', 'Digital Electronics', 'Mathematics I', 'Physics'],
          '2': ['Web Development', 'Data Structures', 'Computer Networks', 'DBMS'],
          '3': ['Cloud Computing', 'Information Security', 'Data Mining', 'Mobile Computing']
      },
      'Cyber Security': {
          '1': ['Cybersecurity Fundamentals', 'Networking Basics', 'Operating Systems Concepts'],
          '2': ['Ethical Hacking', 'Digital Forensics', 'Cryptography'],
          '3': ['Web Security', 'Cloud Security', 'Malware Analysis']
      },
      'AIML': {
          '1': ['Introduction to AI', 'Python Programming', 'Linear Algebra'],
          '2': ['Machine Learning Algorithms', 'Deep Learning', 'Natural Language Processing'],
          '3': ['Computer Vision', 'Reinforcement Learning', 'AI Ethics']
      },
      'AIDS': {
          '1': ['Data Science Fundamentals', 'Statistics for Data Science', 'Database Management'],
          '2': ['Data Mining', 'Big Data Technologies', 'Data Visualization'],
          '3': ['Predictive Analytics', 'Time Series Analysis', 'Business Intelligence']
      },
      'CA': {
          '1': ['Financial Accounting', 'Business Law', 'Economics'],
          '2': ['Cost Accounting', 'Auditing', 'Taxation'],
          '3': ['Financial Management', 'Strategic Management', 'Advanced Accounting']
      },
  };
  const [filteredDepts, setFilteredDepts] = useState([]);
  const [filteredSubjects, setFilteredSubjects] = useState([]);


  // --- Lifecycle and State Effects ---
  /**
   * Effect hook to handle data passed from `AIQuizFactory` component via `location.state`.
   * If AI-generated quiz data is present, it populates tags and sets the CSV file for submission.
   * Clears location state to prevent re-triggering on refresh.
   */
  useEffect(() => {
    if (location.state?.aiQuizData) {
      const { tags: aiTags, fileName: aiFileName, csvContent } = location.state.aiQuizData;
      // If AI provides tags, set them in state.
      if (aiTags?.length > 0) setTags(aiTags);
      setFileName(aiFileName); // Set file name for display.
      // Create a File object from the CSV content string and store it in state for submission.
      setFileToSubmit(new File([csvContent], aiFileName, { type: 'text/csv' }));
      // Clear the location state to prevent re-triggering on subsequent refreshes.
      window.history.replaceState({}, document.title);
    }
  }, [location.state]); // Dependency: location.state to react to navigation with state.

  /**
   * Effect hook to calculate the total weightage of all tags.
   * Updates `totalWeightage` whenever the `tags` array changes.
   */
  useEffect(() => {
    const total = tags.reduce((sum, tag) => sum + parseFloat(tag.weightage || 0), 0);
    setTotalWeightage(total);
  }, [tags]); // Dependency: tags array.

  /**
   * Effect hook to load teacher's details from the authentication token on component mount.
   * Sets `teacherName` and `teacherId`. Handles token expiration errors.
   */
  useEffect(() => {
    try {
      const token = sessionStorage.getItem('token');
      if (!token) throw new Error('Session expired');
      // Decode JWT token to get user details.
      const payloadBase64 = token.split('.')[1];
      const decodedPayload = JSON.parse(
        window.atob(payloadBase64),
      );
      setTeacherName(decodedPayload.userDetails.name);
      setUserDetails(decodedPayload.userDetails);
      setTeacherId(decodedPayload.userDetails.teacher_id);
    } catch (err) {
      console.error("Failed to load teacher details:", err);
      setError('Invalid or expired session. Please log in again.');
      // Optional: navigate('/login') here if you want to force redirect on this error.
    } finally {
      setIsLoading(false); // Finished initial loading.
    }
  }, []); // Empty dependency array means this runs once on mount.

  // --- UI Helper Functions ---
  /** Closes the modal. */
  const closeModal = () => setShowModal(false);
  /** Displays a success modal. */
  const showSuccess = (msg) => { setModalType('success'); setModalMessage(msg); setShowModal(true); };
  /** Displays an error modal. */
  const showError = (msg) => { setModalType('error'); setModalMessage(msg); setShowModal(true); };

  /**
   * Handles changes to form input fields. Manages suggestions for department and subject.
   * @param {Event} e - The change event.
   * @param {string} field - The name of the field being updated.
   */
  const handleInputChange = (e, field) => {
    const value = e.target.type === 'checkbox' ? e.target.checked : e.target.value;
    setFormInput((prev) => ({ ...prev, [field]: value }));

    // Logic for department suggestions.
    if (field === 'department') {
      const filtered = departments.filter((d) => d.toLowerCase().includes(value.toLowerCase()));
      setFilteredDepts(filtered);
      setShowDeptSuggestions(true);
      setFormInput((prev) => ({ ...prev, subjectName: '' })); // Clear subject when department changes.
    }
    // Logic for subject suggestions.
    if (field === 'subjectName') {
      const list = subjects[formInput.department]?.[formInput.year] || [];
      const filtered = list.filter((s) => s.toLowerCase().includes(value.toLowerCase()));
      setFilteredSubjects(filtered);
      setShowSubjSuggestions(true);
    }
    // Logic to clear subject when year changes.
    if (field === 'year') {
      setFormInput((prev) => ({ ...prev, subjectName: '', year: value }));
    }
  };

  /**
   * Handles selection of a suggestion from the dropdown.
   * @param {string} value - The selected suggestion.
   * @param {string} field - The field to update.
   */
  const handleSuggestionClick = (value, field) => {
    setFormInput((prev) => ({ ...prev, [field]: value }));
    if (field === 'department') { setShowDeptSuggestions(false); } else { setShowSubjSuggestions(false); }
  };

  /**
   * Handles changes to individual tag fields (tag name or weightage).
   * @param {number} index - The index of the tag in the array.
   * @param {string} field - The field to update ('tag' or 'weightage').
   * @param {string} value - The new value.
   */
  const handleTagChange = (index, field, value) => {
    const next = [...tags];
    next[index][field] = value;
    setTags(next);
  };

  /** Adds a new empty tag row. */
  const addTag = () => setTags([...tags, { tag: '', weightage: '' }]);

  /** Removes a tag row by index. */
  const removeTag = (i) => { setTags(tags.filter((_, idx) => idx !== i)); };

  /** Navigates to the AI Quiz Factory page. */
  const handleGoToAiFactory = () => navigate('/teacher/ai-quiz-factory');

  // --- Submission Logic ---
  /**
   * Handles the form submission for creating a new assessment.
   * Validates tag weightage, constructs FormData, and sends to the API.
   * Displays feedback via a modal.
   *
   * @param {Event} e - The form submission event.
   */
  const handleSubmit = async (e) => {
    e.preventDefault();

    // Validate total tag weightage.
    if (Math.abs(totalWeightage - 100) > 0.1) { // Allowing a small float deviation
        showError("Total tag weightage must be exactly 100%.");
        return;
    }

    try {
      setIsLoading(true); // Start loading state.
      const token = sessionStorage.getItem('token');
      if (!token) throw new Error('Session expired');

      const formData = new FormData();

      // Append all form fields from state to FormData.
      for (const key in formInput) {
        formData.append(key, formInput[key]);
      }
      formData.append('teacher_id', teacherId);
      formData.append('tags', JSON.stringify(tags)); // Stringify tags array.

      // Logic to handle both AI-generated and manually uploaded files.
      // 1. Prioritize the file received from the AI Factory (stored in `fileToSubmit` state).
      if (fileToSubmit) {
        formData.append('file', fileToSubmit);
      }
      // 2. Fallback to the manual file input if no AI-generated file exists.
      else {
        const fileInput = e.target.elements.file; // Access the DOM file input directly.
        if (fileInput && fileInput.files[0]) {
          formData.append('file', fileInput.files[0]);
        } else {
          // If neither an AI-generated file nor a manually uploaded file is provided, show an error.
          showError("Please upload a CSV file for the assessment.");
          setIsLoading(false);
          return;
        }
      }

      // Send POST request to create the assessment.
      await axios.post(`${API_BASE_URL}/assessments`, formData, {
        headers: {
          Authorization: `Bearer ${token}`,
          // 'Content-Type': 'multipart/form-data' is typically set automatically by browsers for FormData.
        },
      });
      showSuccess('Assessment created successfully!');
    } catch (err) {
      console.error("Assessment creation error:", err);
      const errorMessage = err.response?.data?.message || 'Submission failed. Please check your network connection and try again.';
      showError(errorMessage);
    } finally {
      setIsLoading(false); // End loading state.
    }
  };

  // Display full page loader.
  if (isLoading) return <Loader/>;
  // Display error message if initial data load failed.
  if (error) return <p className="p-6 text-center text-red-600 dark:text-red-400">{error}</p>;

  // UI rendering starts here.
  return (
    <div className="p-6 max-w-4xl mx-auto grid gap-6">
      {/* Card wrapper for the form */}
      <div className="bg-white dark:bg-gray-800 rounded-lg border border-slate-200 dark:border-gray-700 shadow-sm p-6 flex flex-col gap-6">
        <header className="flex items-center justify-between pb-4 border-b border-slate-200 dark:border-gray-700">
          <h1 className="text-md text-slate-600 dark:text-gray-300">You are creating assessment as <span className='font-medium text-slate-700 dark:text-white'>{teacherName}</span></h1>
        </header>

        <form onSubmit={handleSubmit} className="space-y-6">
          {/* Grid for main assessment details */}
          <div className="grid gap-4 md:grid-cols-2">
            {/* Teacher ID (readonly) */}
            <div className="flex flex-col gap-1">
              <label className="text-sm font-medium text-slate-600 dark:text-gray-300">Teacher ID</label>
              <input
                type="text"
                readOnly
                value={teacherId}
                className="w-full bg-slate-100 dark:bg-gray-700 border border-slate-200 dark:border-gray-600 rounded-md px-3 py-2 text-sm text-slate-500 dark:text-gray-400"
              />
            </div>

            {/* Assessment Name Input */}
            <div className="flex flex-col gap-1">
              <label className="text-sm font-medium text-slate-600 dark:text-gray-300">Assessment Name</label>
              <input
                type="text"
                name="name"
                placeholder="Assessment Name"
                className="w-full border border-slate-300 dark:border-gray-600 rounded-md px-3 py-2 text-sm focus:outline-none focus:ring-blue-500 focus:border-blue-500 bg-white dark:bg-gray-700 text-slate-900 dark:text-white placeholder-slate-400 dark:placeholder-gray-500"
                value={formInput.name}
                onChange={(e) => handleInputChange(e, 'name')}
                required
              />
            </div>

            {/* Department with suggestions */}
            <div className="relative flex flex-col gap-1 md:col-span-1">
              <label className="text-sm font-medium text-slate-600 dark:text-gray-300">Department</label>
              <input
                type="text"
                name="department"
                placeholder="Department"
                value={formInput.department}
                onChange={(e) => handleInputChange(e, 'department')}
                className="w-full border border-slate-300 dark:border-gray-600 rounded-md px-3 py-2 text-sm focus:outline-none focus:ring-blue-500 focus:border-blue-500 bg-white dark:bg-gray-700 text-slate-900 dark:text-white placeholder-slate-400 dark:placeholder-gray-500"
                required
                onFocus={() => setShowDeptSuggestions(true)}
                onBlur={() => setTimeout(() => setShowDeptSuggestions(false), 100)} // Delay for click event
              />
              {showDeptSuggestions && filteredDepts.length > 0 && (
                <div className="absolute z-10 mt-1 w-full bg-white dark:bg-gray-800 border border-slate-200 dark:border-gray-700 rounded-md shadow-lg max-h-48 overflow-auto top-full">
                  {filteredDepts.map((d) => (
                    <button
                      type="button"
                      key={d}
                      className="block w-full text-left px-3 py-2 text-sm hover:bg-slate-100 dark:hover:bg-gray-700/50 text-slate-700 dark:text-gray-200"
                      onClick={() => handleSuggestionClick(d, 'department')}
                    >
                      {d}
                    </button>
                  ))}
                </div>
              )}
            </div>

            {/* Year Select */}
            <div className="flex flex-col gap-1">
              <label className="text-sm font-medium text-slate-600 dark:text-gray-300">Year</label>
              <select
                name="year"
                value={formInput.year}
                onChange={(e) => handleInputChange(e, 'year')}
                className="w-full border border-slate-300 dark:border-gray-600 rounded-md px-3 py-2 text-sm focus:outline-none focus:ring-blue-500 focus:border-blue-500 bg-white dark:bg-gray-700 text-slate-900 dark:text-white"
                required
              >
                <option value="">Select Year</option>
                <option value="1">1st Year</option>
                <option value="2">2nd Year</option>
                <option value="3">3rd Year</option>
              </select>
            </div>

            {/* Subject name with suggestions */}
            <div className="relative flex flex-col gap-1 md:col-span-2">
              <label className="text-sm font-medium text-slate-600 dark:text-gray-300">Subject Name</label>
              <input
                type="text"
                name="subjectName"
                placeholder="Subject Name"
                value={formInput.subjectName}
                disabled={!formInput.department || !formInput.year}
                onChange={(e) => handleInputChange(e, 'subjectName')}
                className="w-full border border-slate-300 dark:border-gray-600 rounded-md px-3 py-2 text-sm focus:outline-none focus:ring-blue-500 focus:border-blue-500 disabled:bg-slate-100 dark:disabled:bg-gray-700 bg-white dark:bg-gray-800 text-slate-900 dark:text-white placeholder-slate-400 dark:placeholder-gray-500"
                required
                onFocus={() => setShowSubjSuggestions(true)}
                onBlur={() => setTimeout(() => setShowSubjSuggestions(false), 100)} // Delay for click event
              />
              {showSubjSuggestions && filteredSubjects.length > 0 && (
                <div className="absolute z-10 mt-1 w-full bg-white dark:bg-gray-800 border border-slate-200 dark:border-gray-700 rounded-md shadow-lg max-h-48 overflow-auto top-full">
                  {filteredSubjects.map((s) => (
                    <button
                      type="button"
                      key={s}
                      className="block w-full text-left px-3 py-2 text-sm hover:bg-slate-100 dark:hover:bg-gray-700/50 text-slate-700 dark:text-gray-200"
                      onClick={() => handleSuggestionClick(s, 'subjectName')}
                    >
                      {s}
                    </button>
                  ))}
                </div>
              )}
            </div>

            {/* Dates & times for open and close */}
            {[
              { field: 'openDate', label: 'Open Date', type: 'date' },
              { field: 'openTime', label: 'Start Time', type: 'time' },
              { field: 'closeDate', label: 'Close Date', type: 'date' },
              { field: 'closeTime', label: 'End Time', type: 'time' },
            ].map(({ field, label, type }) => (
              <div key={field} className="flex flex-col gap-1">
                <label className="text-sm font-medium text-slate-600 dark:text-gray-300">{label}</label>
                <input
                  type={type}
                  name={field}
                  value={formInput[field]}
                  onChange={(e) => handleInputChange(e, field)}
                  className="w-full border border-slate-300 dark:border-gray-600 rounded-md px-3 py-2 text-sm focus:outline-none focus:ring-blue-500 focus:border-blue-500 bg-white dark:bg-gray-700 text-slate-900 dark:text-white"
                  required
                />
              </div>
            ))}

            {/* Questions per student input */}
            <div className="flex flex-col gap-1">
              <label className="text-sm font-medium text-slate-600 dark:text-gray-300">Questions per Student</label>
              <input
                type="number"
                name="questionperstudent"
                placeholder="e.g. 10"
                min="1"
                value={formInput.questionperstudent}
                onChange={(e) => handleInputChange(e, 'questionperstudent')}
                className="w-full border border-slate-300 dark:border-gray-600 rounded-md px-3 py-2 text-sm focus:outline-none focus:ring-blue-500 focus:border-blue-500 bg-white dark:bg-gray-700 text-slate-900 dark:text-white placeholder-slate-400 dark:placeholder-gray-500"
                required
              />
            </div>

            {/* Exam duration input */}
            <div className="flex flex-col gap-1">
              <label className="text-sm font-medium text-slate-600 dark:text-gray-300">Exam Duration (minutes)</label>
              <input
                type="number"
                name="examDurationMinutes"
                min="1"
                value={formInput.examDurationMinutes}
                onChange={(e) => handleInputChange(e, 'examDurationMinutes')}
                className="w-full border border-slate-300 dark:border-gray-600 rounded-md px-3 py-2 text-sm focus:outline-none focus:ring-blue-500 focus:border-blue-500 bg-white dark:bg-gray-700 text-slate-900 dark:text-white"
                required
              />
            </div>
          </div>

          {/* Tags section */}
          <div className="flex flex-col gap-4">
            <h2 className="text-sm font-medium text-slate-600 dark:text-gray-300">Question Tags & Weightage</h2>
            <div className="space-y-3">
              {tags.map((t, idx) => (
                <div key={idx} className="grid gap-2 md:grid-cols-[1fr_120px_auto] items-center">
                  <input
                    type="text"
                    placeholder="Tag (e.g. CS)"
                    value={t.tag}
                    onChange={(e) => handleTagChange(idx, 'tag', e.target.value)}
                    className="border border-slate-300 dark:border-gray-600 rounded-md px-3 py-2 text-sm focus:outline-none focus:ring-blue-500 focus:border-blue-500 bg-white dark:bg-gray-700 text-slate-900 dark:text-white placeholder-slate-400 dark:placeholder-gray-500"
                    required
                  />
                  <input
                    type="number"
                    placeholder="Weightage %"
                    min="0"
                    max="100"
                    step="0.1"
                    value={t.weightage}
                    onChange={(e) => handleTagChange(idx, 'weightage', e.target.value)}
                    className="border border-slate-300 dark:border-gray-600 rounded-md px-3 py-2 text-sm focus:outline-none focus:ring-blue-500 focus:border-blue-500 bg-white dark:bg-gray-700 text-slate-900 dark:text-white placeholder-slate-400 dark:placeholder-gray-500"
                    required
                  />
                  {tags.length > 1 && (
                    <button
                      type="button"
                      onClick={() => removeTag(idx)}
                      className="p-2 rounded-md hover:bg-slate-100 dark:hover:bg-gray-700/50 transition"
                      aria-label={`Remove tag ${t.tag}`}
                    >
                      <CloseIcon className="w-4 h-4 text-slate-500 dark:text-gray-400" />
                    </button>
                  )}
                </div>
              ))}
            </div>
            <div className="flex items-center justify-between text-sm">
              <button
                type="button"
                onClick={addTag}
                className="flex items-center gap-2 font-medium text-blue-600 dark:text-blue-400 hover:underline"
              >
                <PlusIcon className="w-4 h-4" /> Add Tag
              </button>
              <span
                className={`font-medium ${Math.abs(totalWeightage - 100) > 0.1 ? 'text-red-600 dark:text-red-400' : 'text-slate-600 dark:text-gray-300'}`}
              >
                Total: {totalWeightage}%
              </span>
            </div>
          </div>

          {/* File upload section */}
          <div className="flex flex-col gap-1">
            <label className="text-sm font-medium text-slate-600 dark:text-gray-300">Upload CSV</label>
            <div className="relative flex items-center gap-3 border border-slate-300 dark:border-gray-600 rounded-md px-3 py-2 text-sm bg-white dark:bg-gray-700">
              <UploadIcon className="w-4 h-4 text-slate-500 dark:text-gray-400" />
              <input
                type="file"
                id="file-upload"
                name="file"
                accept=".csv"
                onChange={(e) => {
                    setFileName(e.target.files?.[0]?.name || '');
                    // Clear the AI-generated file if a manual one is chosen.
                    if(e.target.files?.[0]) setFileToSubmit(null);
                }}
                className="absolute inset-0 opacity-0 cursor-pointer"
                aria-label="Upload CSV file for questions"
              />
              <span className="truncate select-none text-slate-900 dark:text-white">{fileName || 'Choose CSV file'}</span>
            </div>
          </div>

          {/* AI Factory Section */}
          <div className="md:col-span-2 p-4 bg-blue-50/50 dark:bg-blue-900/20 border-2 border-dashed border-blue-200 dark:border-blue-700 rounded-lg space-y-4">
            <div className="flex items-center gap-2">
              <Bot className="w-5 h-5 text-blue-600 dark:text-blue-400" />
              <h4 className="font-semibold text-slate-800 dark:text-white">Generate Questions with AI</h4>
            </div>
            <p className="text-sm text-slate-600 dark:text-gray-300">Alternatively, use our AI to generate a question CSV for you based on a PDF document.</p>
            <div className="text-left">
              <button type="button" onClick={handleGoToAiFactory} className="inline-flex items-center gap-2 px-4 py-2 text-sm font-semibold bg-blue-600 text-white rounded-lg hover:bg-blue-700 dark:hover:bg-blue-500">Go to AI Quiz Factory</button>
            </div>
          </div>

          {/* Submit button */}
          <div className="flex justify-end">
            <button
              type="submit"
              disabled={isLoading}
              className="bg-blue-600 text-white px-6 py-2 rounded-md font-semibold hover:bg-blue-700 dark:hover:bg-blue-500 transition disabled:opacity-60 disabled:cursor-not-allowed"
            >
              {isLoading ? 'Uploading…' : 'Upload Questions'}
            </button>
          </div>
        </form>
      </div>

      {/* Modal for submission feedback */}
      {showModal && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-900/50 dark:bg-gray-950/70 p-4">
          <div className="bg-white dark:bg-gray-800 rounded-lg shadow-lg max-w-sm w-full p-6 space-y-4" role="dialog" aria-modal="true" aria-labelledby="modal-title">
            <div className="flex items-center gap-2">
              {modalType === 'success' ? <CheckIcon className="w-5 h-5 text-green-600 dark:text-green-400" /> : <AlertIcon className="w-5 h-5 text-red-600 dark:text-red-400" />}
              <h3 id="modal-title" className="text-base font-semibold text-slate-800 dark:text-white">{modalType === 'success' ? 'Success' : 'Error'}</h3>
            </div>
            <p className="text-sm text-slate-600 dark:text-gray-300">{modalMessage}</p>
            <div className="flex justify-end gap-2">
              <button
                onClick={closeModal}
                className="bg-slate-100 dark:bg-gray-700 text-slate-700 dark:text-gray-200 px-4 py-1.5 rounded-md text-sm font-medium hover:bg-slate-200 dark:hover:bg-gray-600 transition"
              >
                Close
              </button>
              {modalType === 'success' && (
                <button
                  onClick={() => { closeModal(); navigate('/teacher-dashboard'); }}
                  className="bg-blue-600 text-white px-4 py-1.5 rounded-md text-sm font-medium hover:bg-blue-700 dark:hover:bg-blue-500 transition"
                >
                  Go to Dashboard
                </button>
              )}
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default AddQuestion;
