import { ArrowLeft, Check, Star, Tag } from 'lucide-react'; // Icons for back, check, star, tag
import { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { useBreadcrumbContext } from '../../../contexts/BreadcrumbContext'; // Breadcrumb context hook

/**
 * ViewAIQuiz component displays the generated quiz questions and their correct answers.
 * This component is intended for reviewing questions generated by the AI Quiz Factory.
 * Questions data is retrieved from session storage.
 *
 * @returns {JSX.Element} The AI-generated quiz display UI.
 */
const ViewAIQuiz = () => {
    // State to store the list of questions to display.
    const [questions, setQuestions] = useState([]);
    // State to store the title of the quiz (e.g., "AI Generated Quiz").
    const [pageTitle, setPageTitle] = useState('View Generated Quiz');
    const { setCrumbs } = useBreadcrumbContext(); // Hook to set breadcrumbs.
    const navigate = useNavigate(); // Hook for programmatic navigation.

    /**
     * Effect hook to load quiz data from session storage on component mount.
     * If no data is found, redirects back to the AI Quiz Factory.
     * Also sets the breadcrumbs.
     */
    useEffect(() => {
        try {
            const dataString = sessionStorage.getItem('quizToView');
            if (dataString) {
                const data = JSON.parse(dataString);
                setQuestions(data.questions || []); // Set questions, ensuring it's an array.
                setPageTitle(data.title || 'View Generated Quiz'); // Set page title.
            } else {
                // If no data is found, redirect to the AI Quiz Factory.
                navigate('/teacher/ai-quiz-factory');
            }
        } catch (error) {
            console.error("Failed to parse quiz data:", error);
            // On parsing error, also redirect.
            navigate('/teacher/ai-quiz-factory');
        }
        // Set breadcrumbs specific to this view.
        setCrumbs([
            { name: 'Add Questions', path: '/add-question' },
            { name: 'AI Quiz Factory', path: `/teacher/ai-quiz-factory` },
            { name: 'View AI Generated Questions', path: `/teacher/view-quiz` }
        ]);
    }, [navigate, setCrumbs]); // Dependencies: navigate (for redirection), setCrumbs (for breadcrumbs).

    return (
        <div className="space-y-6">
            {/* Header Section */}
            <header>
                {/* Button to navigate back to the AI Quiz Factory. */}
                <button onClick={() => navigate(-1)} className="flex items-center gap-2 text-sm font-semibold text-slate-600 dark:text-gray-300 hover:text-slate-800 dark:hover:text-white transition mb-2">
                    <ArrowLeft size={16} />
                    Return to AI Factory
                </button>
                <h1 className="text-2xl font-bold text-slate-800 dark:text-white">{pageTitle}</h1>
                <p className="text-slate-500 dark:text-gray-400 mt-1">Review the questions and answers generated by the AI.</p>
            </header>

            {/* Questions List */}
            <div className="space-y-6">
                {questions.length > 0 ? (
                    questions.map((q, i) => (
                        <div key={`q-view-${i}`} className="bg-white dark:bg-gray-800 p-6 rounded-xl border border-slate-200 dark:border-gray-700 shadow-sm">
                            {/* Question Header */}
                            <div className="flex justify-between items-start gap-4 mb-4">
                                <h4 className="text-base font-semibold text-slate-800 dark:text-white leading-snug">
                                    <span className="text-blue-600 dark:text-blue-400 font-bold">Q{i + 1}:</span> {q.question}
                                </h4>
                            </div>

                            {/* Options List */}
                            <ul className="space-y-2 mb-4">
                                {(q.options || []).map((option, j) => (
                                    <li
                                        key={`opt-view-${i}-${j}`}
                                        className={`flex items-center justify-between p-3 rounded-lg text-sm transition-all border
                                            ${option === q.answer
                                                ? 'bg-green-50 dark:bg-green-900/20 text-green-800 dark:text-green-400 font-semibold border-green-300 dark:border-green-700'
                                                : 'bg-slate-50 dark:bg-gray-700 text-slate-700 dark:text-gray-200 border-slate-200 dark:border-gray-600'}`
                                        }
                                    >
                                        <span>{option}</span>
                                        {/* Display check icon next to the correct answer. */}
                                        {option === q.answer && <Check size={18} className="text-green-600 dark:text-green-400" />}
                                    </li>
                                ))}
                            </ul>

                            {/* Footer with Tags and Marks */}
                            <div className="flex flex-wrap items-center gap-x-4 gap-y-2 pt-4 border-t border-slate-100 dark:border-gray-700 text-xs text-slate-600 dark:text-gray-300 font-medium">
                                <div className="flex items-center gap-1.5 bg-slate-100 dark:bg-gray-700 px-2 py-1 rounded-full">
                                    <Tag size={14} className="text-slate-500 dark:text-gray-400" />
                                    <span>Tag: <span className="font-bold text-slate-800 dark:text-white">{q.tags || 'N/A'}</span></span>
                                </div>
                                <div className="flex items-center gap-1.5 bg-slate-100 dark:bg-gray-700 px-2 py-1 rounded-full">
                                    <Star size={14} className="text-slate-500 dark:text-gray-400" />
                                    <span>Mark: <span className="font-bold text-slate-800 dark:text-white">{q.mark || '1'}</span></span>
                                </div>
                            </div>
                        </div>
                    ))
                ) : (
                    // Empty state: Displayed when no questions are available for review.
                    <div className="text-center py-20 text-slate-500 dark:text-gray-400 bg-white dark:bg-gray-800 rounded-lg border border-slate-200 dark:border-gray-700">
                        <h3 className="text-xl font-semibold">No Questions to Display</h3>
                        <p className="mt-2">Please return to the AI Factory to generate or load questions.</p>
                    </div>
                )}
            </div>
        </div>
    );
};

export default ViewAIQuiz;
