import { ArrowLeft, Check, Star, Tag } from 'lucide-react';
import { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { useBreadcrumbContext } from '../../../contexts/BreadcrumbContext';

const ViewAIQuiz = () => {
    const [questions, setQuestions] = useState([]);
    const [pageTitle, setPageTitle] = useState('View Generated Quiz');
    const { setCrumbs } = useBreadcrumbContext();
    const navigate = useNavigate();

    // On component mount, load the data from sessionStorage
    useEffect(() => {
        try {
            const dataString = sessionStorage.getItem('quizToView');
            if (dataString) {
                const data = JSON.parse(dataString);
                setQuestions(data.questions || []);
                setPageTitle(data.title || 'View Generated Quiz');
            } else {
                navigate('/teacher/ai-quiz-factory');
            }
        } catch (error) {
            console.error("Failed to parse quiz data:", error);
            navigate('/teacher/ai-quiz-factory');
        }
        setCrumbs([
            { name: 'Add Questions', path: '/add-question' },
            { name: 'AI Quiz Factory', path: `/teacher/ai-quiz-factory` },
            { name: 'View Ai Generated Questions', path: `/teacher/view-quiz` }
        ]);
    }, [navigate, setCrumbs]);

    return (
        <div className="space-y-6">
            {/* Header */}
            <header>
                <button onClick={() => navigate(-1)} className="flex items-center gap-2 text-sm font-semibold text-slate-600 hover:text-slate-800 transition mb-2">
                    <ArrowLeft size={16} />
                    Return to AI Factory
                </button>
                <h1 className="text-2xl font-bold text-slate-800">{pageTitle}</h1>
                <p className="text-slate-500 mt-1">Review the questions and answers generated by the AI.</p>
            </header>

            {/* Questions List */}
            <div className="space-y-6">
                {questions.length > 0 ? (
                    questions.map((q, i) => (
                        <div key={`q-view-${i}`} className="bg-white p-6 rounded-xl border border-slate-200 shadow-sm">
                            {/* Question Header */}
                            <div className="flex justify-between items-start gap-4 mb-4">
                                <h4 className="text-base font-semibold text-slate-800 leading-snug">
                                    <span className="text-blue-600 font-bold">Q{i + 1}:</span> {q.question}
                                </h4>
                            </div>
                            
                            {/* Options List */}
                            <ul className="space-y-2 mb-4">
                                {(q.options || []).map((option, j) => (
                                    <li
                                        key={`opt-view-${i}-${j}`}
                                        className={`flex items-center justify-between p-3 rounded-lg text-sm transition-all border
                                            ${option === q.answer 
                                                ? 'bg-green-50 text-green-800 font-semibold border-green-300' 
                                                : 'bg-slate-50 text-slate-700 border-slate-200'}`
                                        }
                                    >
                                        <span>{option}</span>
                                        {option === q.answer && <Check size={18} className="text-green-600" />}
                                    </li>
                                ))}
                            </ul>

                            {/* Footer with Tags and Marks */}
                            <div className="flex flex-wrap items-center gap-x-4 gap-y-2 pt-4 border-t border-slate-100 text-xs text-slate-600 font-medium">
                                <div className="flex items-center gap-1.5 bg-slate-100 px-2 py-1 rounded-full">
                                    <Tag size={14} className="text-slate-500" />
                                    <span>Tag: <span className="font-bold text-slate-800">{q.tags || 'N/A'}</span></span>
                                </div>
                                <div className="flex items-center gap-1.5 bg-slate-100 px-2 py-1 rounded-full">
                                    <Star size={14} className="text-slate-500" />
                                    <span>Mark: <span className="font-bold text-slate-800">{q.mark || '1'}</span></span>
                                </div>
                            </div>
                        </div>
                    ))
                ) : (
                    <div className="text-center py-20 text-slate-500 bg-white rounded-lg border border-slate-200">
                        <h3 className="text-xl font-semibold">No Questions to Display</h3>
                        <p className="mt-2">Please return to the AI Factory to generate or load questions.</p>
                    </div>
                )}
            </div>
        </div>
    );
};

export default ViewAIQuiz;


